---
title: "Take-Home Exercise 2"
author: "Leonard Lee"
format:
  html:
    code-fold: true
    code-summary: "Show me the good stuff"
execute:
  warning: false
date: "18 May 2023"
date-modified: "`r Sys.Date()`"
---

Weight field calculating number of times target communicated with the source.

(multiple source to target links at diff times)

In and out weight (In degree and out degree)

Aggregate out big network

(In class ex reference to weight field)

```{r}
pacman::p_load(igraph, tidygraph, ggraph, 
               visNetwork, lubridate, clock,
               tidyverse, graphlayouts, jsonlite)


```

```{r}
MC2 <- fromJSON("data/mc2_challenge_graph.json")

```

```{r}
MC2_nodes <- as_tibble(MC2$nodes) %>%
  select(id,shpcountry, rcvcountry) #using select function to reorganise into desired order of columns

MC2_edges <- as_tibble(MC2$links) %>%
  select(source, target, valueofgoods_omu, valueofgoodsusd, weightkg, hscode, arrivaldate)

```


```{r}
MC2_edges <- MC2_edges %>%
  mutate(Month = month(arrivaldate,
                        label = TRUE,
                        abbr = FALSE))

# rename columns
MC2_edges <- MC2_edges %>%
  rename('Source' = 'source', 
         'Target' = 'target', 
         'Value_OMU' = 'valueofgoods_omu', 
         'Value_USD' = 'valueofgoodsusd', 
         'Weight_KG' = 'weightkg', 
         'HS_Code' = 'hscode', 
         'Arrival_Date' = 'arrivaldate')
```
