---
title: "In-Class Exercise 4"
author: "Leonard Lee"
date: "5 May 2023"
date-modified: "`r Sys.Date()`"
execute:
  echo: True
  eval: True
  warning: False
---

# Load Packages

```{r} 
pacman::p_load(rstatix, gt, patchwork, webshot2, tidyverse)
```

#Importing the data

```{r}

exam_data4 <- read_csv("data/Exam_data.csv")

```

::: panel-tabset

## The plot
```{r}
#| echo: False
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data4,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line()

```
## The code

```{r}
#| eval: False
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data4,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line()

```

:::

::: {.callout-note}
We can see that the points deviate significantly from the straight diagonal line. This is a clear indication that the set of data is not normally distributed.

:::

##Combining Statistical Results and 


::: panel-tabset

## The plot
```{r}
#| echo: false

qq <- ggplot(exam_data4,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line()

sw_t <- exam_data4 %>%
  shapiro_test(ENGLISH) %>%
  gt()

tmp <- tempfile(fileext = '.png')
gtsave(sw_t, tmp)
table_png <- png::readPNG(tmp, native = TRUE)

qq + table_png
```

## The code
```{r}
#| eval: false

qq <- ggplot(exam_data4,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line()

sw_t <- exam_data4 %>%
  shapiro_test(ENGLISH) %>%
  gt()

tmp <- tempfile(fileext = '.png')
gtsave(sw_t, tmp)
table_png <- png::readPNG(tmp, native = TRUE)

qq + table_png
```

:::