---
title: "Take-Home Exercise 1"
author: "Leonard Lee"
---

# Load Packages

```{r}
pacman::p_load(readr, ggrepel, patchwork,
               ggthemes, hrbrthemes, ggiraph, plotly, 
               patchwork, DT, tidyverse)
```

# Import the Data

```{r}

Fdata <- read_csv("data/FinancialJournal.csv")


```

```{r}

Jdata <- read_csv("data/Participants.csv")

```

#Cleaning and Preparing the Data

##Check for Missing Values

```{r}
any(is.na(Fdata))

any(is.na(Jdata))
```


# Merge Data to compare expenses to Joviality

``` {r}


# Group the data frame by participant ID and calculate the sum of expenses for each group

summed_df <- aggregate(Fdata$amount, by=list(Fdata$participantId), FUN=sum)

# Rename the columns in the resulting data frame

colnames(summed_df) <- c("participantId", "total_expenses")

# Save the resulting data frame to a new CSV file

write.csv(summed_df, file="data/summed_expenses.csv", row.names=FALSE)

```

```{r}
# Merge the two data frames on the 'participant ID' column
merged_data <- merge(Jdata, summed_df, by="participantId")

# Save the merged data frame to a new CSV file

write.csv(merged_data, file="merged_data.csv", row.names=FALSE)
```

## Data are in incorrect format

```{r}

Fdata$amount <- as.integer(Fdata$amount)

```

::: {.callout-note collapse="true"}
:::

::: panel-tabset
### Header

## 

## 
:::
